# Generated by Django 2.0.3 on 2018-04-07 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('households', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isOn', models.BooleanField(default=False)),
                ('isOnline', models.BooleanField(default=False)),
                ('deviceType', models.CharField(choices=[('PLUG', 'Plug'), ('SOCKET', 'Socket')], max_length=255)),
                ('kitPaidFor', models.BooleanField(default=True)),
                ('claimedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('claimedBy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='households.Household')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAttributes_Plug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOn', models.BooleanField(default=False)),
                ('lastOn', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceAttributes_Socket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOn', models.BooleanField(default=False)),
                ('lastOn', models.DateTimeField(blank=True, null=True)),
                ('brightness', models.PositiveSmallIntegerField()),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceNetworkAttributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOnline', models.BooleanField(default=False)),
                ('lastOnline', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ManufacturedDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='kit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.Kit'),
        ),
    ]
