# Generated by Django 2.0.3 on 2018-04-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='kit',
        ),
        migrations.RemoveField(
            model_name='device',
            name='kitPaidFor',
        ),
        migrations.AlterField(
            model_name='deviceattributes_socket',
            name='brightness',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
