# Generated by Django 2.0.3 on 2018-04-09 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20180407_2212'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kit',
        ),
        migrations.DeleteModel(
            name='ManufacturedDevice',
        ),
        migrations.AlterField(
            model_name='device',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='households.Household'),
        ),
    ]
