# Generated by Django 2.0.3 on 2018-04-09 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20180409_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceattributes_plug',
            name='device',
        ),
        migrations.RemoveField(
            model_name='deviceattributes_socket',
            name='device',
        ),
    ]
