# Generated by Django 2.0.3 on 2018-04-07 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20180401_1618'),
        ('authentication', '0004_auto_20180403_0352'),
    ]

    operations = [
    ]
